[package]
name = "primes"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "all"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1"

[dev-dependencies]
criterion = "0.3.6"

[lib]
bench = false
